defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

  [[tls.certificates]]
    certFile = "/aiwiki.co.pem"
    keyFile = "/aiwiki.co.key"

  [entryPoints.foo]
  address = ":8080"
  [entryPoints.foo.auth]
    [entryPoints.foo.auth.basic]
      usersFile = "/.htpasswd"

[api]
entryPoint = "foo"


# vim:filetype=yaml
